# Font configuration
[font]
  normal = { family = "Agave Nerd Font Mono", style = "Regular" }
  size = 14.0

[general]
working_directory = "/orbit"

# Shell configuration
[terminal.shell]
program = "C:/Program Files/PowerShell/7/pwsh.exe"

# Enviroment variables
[env]
VIMRUNTIME = "C:/App/vim/vim91"
